default:
  outputs:

    dev:
      type: postgres
      threads: 10
      host: localhost
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASS') }}"
      dbname: dbt
      schema: warehouse
  target: dev